POST http://localhost:8080/users
Content-Type: application/json

{"login":"obhajoba","email":"obhajoba@test.cz","name":"Obhajoba","surname":"Prvni","gender":"male","role":"role","password":"test"}

###